language: android
android:
  components:
  - build-tools-29.0.2
  - android-28
  - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

cache:
  directories:
    - '$HOME/.m2/repository'

